### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by jungdu** [gjbae1212/hit-counter#6]
### Todo List
- [ ] Change main logo 
- [ ] Change styles in SHOW STREAM section
- [ ] Add simple usage on
- [ ] Change graph size to responsive

**Comment by jungdu** [comment]
![Hits](https://user-images.githubusercontent.com/21999598/88407205-bcc24880-ce0c-11ea-9324-69999b4209ca.png)
How do you think about this logo @gjbae1212
